[tool.poetry]
name = "tictactoe"
version = "0.1.0"
description = ""
authors = ["Richie Goulazian <rgoulazian@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
